# Generated by Django 3.1.7 on 2021-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='e_logo.jpg', upload_to='profile_pics'),
        ),
    ]
