# Generated by Django 5.1.4 on 2025-05-21 10:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='explicit_image',
            field=cloudinary.models.CloudinaryField(default='e_logo.jpg', max_length=255, verbose_name='explicit_test_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='e_logo.jpg', upload_to='profile_pics/'),
        ),
    ]
