# Generated by Django 5.1.4 on 2025-05-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_explicit_image_alter_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='explicit_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='img2',
            field=models.ImageField(default='e_logo.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='e_logo.jpg', upload_to='profile_pics'),
        ),
    ]
