# Generated by Django 5.0.14 on 2025-05-23 02:36

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_explicit_image_profile_img2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, default='e_logo.jpg', force_format=None, keep_meta=True, quality=85, scale=None, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
