# Generated by Django 5.0.14 on 2025-05-23 03:19

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, default='https://res.cloudinary.com/djl7dtnme/image/upload/v1747969887/media/profile_pics/e_logo.jpg', force_format=None, keep_meta=True, quality=85, scale=None, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
