# Generated by Django 5.0.14 on 2025-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_approval_status_profile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
    ]
