# Generated by Django 5.0.14 on 2025-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_booking_options_booking_special_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default='a@g.com', max_length=254),
        ),
    ]
