# Generated by Django 5.0.14 on 2025-07-28 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_facility_alter_booking_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_gallery/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'jpg', 'webp'])])),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the work')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Gallery Image',
                'verbose_name_plural': 'Event Gallery Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
