# Generated by Django 5.0.14 on 2025-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Eventmanagement', 'Eventmanagement'), ('MakeupArtsist', 'Makeup Artsist'), ('Cakeshops', 'Cake shops'), ('MehandiArtist', 'Mehandi Artist'), ('Photographer', 'Photographer'), ('WeddingVenues', 'Wedding Venues'), ('CarsAndBuses', 'Cars and Buses'), ('InvitationCards', 'Invitation Cards'), ('Stagedecorator', 'Stage decorator'), ('CateringService', 'Catering Service')], max_length=20),
        ),
    ]
